dig = str(input('Digite algo: '))
print('O tipo primitivo desse valor é {}'.format(type(dig)))
print('So tem espaços? {}'.format(dig.isspace()))
print('E um numero? {}'.format(dig.isnumeric()))
print('E alfabético? {}'.format(dig.isalpha()))
print('E alfanumerico? {}'.format(dig.isalnum()))
print('Esta em maiusculas? {}'.format(dig.isupper()))
print('Esta em minusculas? {}'.format(dig.islower()))
print('Esta capitalizada? {}'.format(dig.istitle()))
